### ISSUE TITLE
new data folder do not contain certain data

### ISSUE THREAD

**Issue by gaiac** [Dr-Patient/Progeni#1]
the new_data folder do not contain protein.txt, drug.txt, se.txt and disease.txt, therefore, there's no way of knowing the labels of the mat_drug_disease, mat_drug_protein, mat_drug_se, etc...

**Comment by Dr-Patient** [comment]
Hi! Sorry for the late reply. I have re-uploaded a **data_new.tgz** with .tsv files describing the labels of the matrices. Please see the new README also :)
